name: Prettier Check
on:
  push:
    branches:
      - master
      - actions
  pull_request:
    branches:
      - master
      - actions
jobs:
  prettier-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: pnpm

      - name: Install
        run: pnpm install
